package org.pankratzlab.common.stats;

import org.pankratzlab.common.Logger;

/**
 * Functional interface for performing an SVD regression.
 */
public interface SVDProvider {

  /**
   * @param deps
   * @param indeps
   * @param verbose
   * @param log
   */
  RegressionResult performSVDRegression(double[] deps, double[][] indeps, boolean verbose,
                                        Logger log);

  /**
   * Wrapper for the betas and invP values generated by SVD regression.
   */
  public static class RegressionResult {

    private double[] betas;
    private double[][] invP;

    public RegressionResult(double[] betas, double[][] invP) {
      super();
      this.betas = betas;
      this.invP = invP;
    }

    public double[] getBetas() {
      return betas;
    }

    public double[][] getInvP() {
      return invP;
    }
  }
}
